// admin/src/pages/ai/ToolRegistryPage.vue
<!--
作者: Cursor Agent
日期: 2026-05-26
修改功能: 技能与工具 · 交互对齐原型 · 样式对齐 admin 整站
-->
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

import {
  countRuntimePublishedStats,
  countSpecReadyStats,
  matrixStatusClass,
  matrixStatusLabel,
  mergeSkillRegistryWithApi,
  type SkillRegistryRowView,
} from '@/entities/tool-registry/skill-registry-catalog'
import {
  MOCK_TOOL_B_ROWS,
  MOCK_TOOL_C_ROWS,
  type ToolRegistryRow,
} from '@/entities/tool-registry/tool-registry-mock'
import {
  SKILL_REGISTRY_PAGE,
  SKILL_REGISTRY_RUNTIME,
  TOOL_REGISTRY_TABLE,
} from '@/entities/tool-registry/tool-registry-copy'
import {
  isRowEnabled,
  loadToolRegistryState,
  persistToggle,
  resetToolRegistryDemo,
  type ToolRegistryStored,
} from '@/entities/tool-registry/tool-registry-storage'
import {
  explainSkillSpecApiError,
  listSkillOperationSpecs,
  type SkillOperationSpecSummary,
} from '@/shared/api/admin-skill-specs'
import { adminToastInfo, adminToastSuccess } from '@/shared/lib/admin-toast'
import AdminPage from '@/shared/ui/AdminPage.vue'
import {
  AdminPageHeader,
  UiButton,
  UiEnableCheckbox,
  UiInput,
  UiStatChip,
  UiTableEmptyRow,
  adminTableHostOverflowClass,
} from '@/shared/ui'

import SkillOperationDrawer from '@/pages/ai/SkillOperationDrawer.vue'
import SkillRegistryTable from '@/pages/ai/SkillRegistryTable.vue'

type RegistryTab = 'skills' | 'tools-b' | 'tools-c' | 'audit'

const apiItems = ref<SkillOperationSpecSummary[]>([])
const loading = ref(false)
const listError = ref<string | null>(null)
const skillFilter = ref('')
const showPublishedOnly = ref(false)
const activeTab = ref<RegistryTab>('skills')

const detailSkillId = ref<string | null>(null)
const detailRow = ref<SkillRegistryRowView | null>(null)

const mergedRows = computed(() => mergeSkillRegistryWithApi(apiItems.value))

const skillListFiltered = computed(() => {
  if (!showPublishedOnly.value) return mergedRows.value
  return mergedRows.value.filter((r) => r.isRuntimePublished)
})

const filteredSkillRows = computed(() => {
  const kw = skillFilter.value.trim().toLowerCase()
  if (!kw) return skillListFiltered.value
  return skillListFiltered.value.filter(
    (r) =>
      r.skillId.toLowerCase().includes(kw) ||
      r.summary.toLowerCase().includes(kw) ||
      r.userFlow.toLowerCase().includes(kw) ||
      r.exchangeAction.toLowerCase().includes(kw),
  )
})

const skillTableFiltered = computed(
  () => skillFilter.value.trim().length > 0 || showPublishedOnly.value,
)

const allRegistryRows = computed(() => [
  ...mergedRows.value.map((r) => ({
    stableId: r.skillId,
    entryClass: 'A' as const,
    defaultEnabled: r.defaultEnabled,
  })),
  ...MOCK_TOOL_B_ROWS.map((r) => ({
    stableId: r.stableId,
    entryClass: r.entryClass,
    defaultEnabled: r.defaultEnabled,
  })),
  ...MOCK_TOOL_C_ROWS.map((r) => ({
    stableId: r.stableId,
    entryClass: r.entryClass,
    defaultEnabled: r.defaultEnabled,
  })),
])

const defaultEnabledMap = computed(() => {
  const m: Record<string, boolean> = {}
  for (const r of allRegistryRows.value) m[r.stableId] = r.defaultEnabled
  return m
})

const allIds = computed(() => allRegistryRows.value.map((r) => r.stableId))

const store = ref<ToolRegistryStored>({ enabled: {}, audit: [] })

function initStore() {
  store.value = loadToolRegistryState(allIds.value, defaultEnabledMap.value)
}

const specStats = computed(() => countSpecReadyStats(mergedRows.value))
const runtimeStats = computed(() => countRuntimePublishedStats(mergedRows.value))

const stats = computed(() => {
  const countOn = (rows: { stableId: string; defaultEnabled: boolean }[]) =>
    rows.filter((r) => isRowEnabled(r.stableId, r.defaultEnabled, store.value)).length
  return {
    aOn: countOn(
      mergedRows.value.map((r) => ({ stableId: r.skillId, defaultEnabled: r.defaultEnabled })),
    ),
    aTotal: mergedRows.value.length,
    bOn: countOn(MOCK_TOOL_B_ROWS),
    bTotal: MOCK_TOOL_B_ROWS.length,
    cOn: countOn(MOCK_TOOL_C_ROWS),
    cTotal: MOCK_TOOL_C_ROWS.length,
    audit: store.value.audit.length,
  }
})

async function loadList() {
  loading.value = true
  listError.value = null
  try {
    const res = await listSkillOperationSpecs()
    apiItems.value = res.items
    initStore()
  } catch (e) {
    listError.value = explainSkillSpecApiError(e, '加载技能列表失败')
    apiItems.value = []
    initStore()
  } finally {
    loading.value = false
  }
}

function resetDemo() {
  store.value = resetToolRegistryDemo(allIds.value, defaultEnabledMap.value)
  adminToastSuccess(SKILL_REGISTRY_PAGE.resetSuccess)
}

function onSkillToggle(row: SkillRegistryRowView, enabled: boolean) {
  if (row.matrixStatus === 'tbd' && enabled) {
    adminToastInfo(SKILL_REGISTRY_PAGE.enableWarning)
  }
  store.value = persistToggle({
    stableId: row.skillId,
    entryClass: 'A',
    enabled,
    prev: store.value,
  })
}

function onToolToggle(row: ToolRegistryRow, enabled: boolean) {
  if (row.matrixStatus === 'tbd' && enabled) {
    adminToastInfo(SKILL_REGISTRY_PAGE.enableWarning)
  }
  store.value = persistToggle({
    stableId: row.stableId,
    entryClass: row.entryClass,
    enabled,
    prev: store.value,
  })
}

function openSkillDetail(skillId: string) {
  detailSkillId.value = skillId
  detailRow.value = mergedRows.value.find((r) => r.skillId === skillId) ?? null
}

function closeDrawer() {
  detailSkillId.value = null
  detailRow.value = null
}

async function onPublished() {
  await loadList()
  const id = detailSkillId.value
  if (!id) return
  detailRow.value = mergedRows.value.find((r) => r.skillId === id) ?? null
}

function toolRowEnabled(row: ToolRegistryRow): boolean {
  return isRowEnabled(row.stableId, row.defaultEnabled, store.value)
}

function toolRowClass(row: ToolRegistryRow): string {
  const parts: string[] = []
  if (row.matrixStatus === 'tbd') parts.push('admin-tool-registry-row--tbd')
  if (!toolRowEnabled(row)) parts.push('admin-tool-registry-row--disabled')
  return parts.join(' ')
}

const auditRows = computed(() => [...store.value.audit].reverse())

onMounted(() => {
  void loadList()
})
</script>

<template>
  <AdminPage width="full" class="admin-tool-registry-page">
    <AdminPageHeader
      :title="SKILL_REGISTRY_PAGE.title"
      :description="SKILL_REGISTRY_PAGE.description"
      :badges="[
        { label: SKILL_REGISTRY_PAGE.tagTrading, tone: 'violet' },
        { label: SKILL_REGISTRY_PAGE.tagPreview, tone: 'sky' },
      ]"
      dev-meta="pageId · ai.tool-registry · GET/POST v1/admin/skill-specs/*"
      :error="listError"
    >
      <template #actions>
        <UiButton type="button" variant="secondary" size="sm" @click="resetDemo">
          {{ SKILL_REGISTRY_PAGE.resetButton }}
        </UiButton>
      </template>
    </AdminPageHeader>

    <div class="admin-tool-registry-stats mb-4 grid grid-cols-2 gap-3 lg:grid-cols-5">
      <div class="admin-panel admin-tool-registry-stat-card rounded-lg px-4 py-3">
        <p class="text-xs text-slate-500">{{ SKILL_REGISTRY_PAGE.statTradingEnabled }}</p>
        <p class="mt-1 text-2xl font-semibold tabular-nums text-white">
          {{ stats.aOn }}
          <span class="text-base font-normal text-slate-500">/ {{ stats.aTotal }}</span>
        </p>
      </div>
      <div class="admin-panel admin-tool-registry-stat-card rounded-lg px-4 py-3">
        <p class="text-xs text-slate-500">{{ SKILL_REGISTRY_PAGE.statSpecReady }}</p>
        <p
          class="mt-1 text-2xl font-semibold tabular-nums"
          :class="specStats.complete === specStats.publishRequired ? 'text-emerald-300' : 'text-white'"
        >
          {{ specStats.complete }}
          <span class="text-base font-normal text-slate-500">/ {{ specStats.publishRequired }}</span>
        </p>
      </div>
      <div class="admin-panel admin-tool-registry-stat-card rounded-lg px-4 py-3">
        <p class="text-xs text-slate-500">{{ SKILL_REGISTRY_RUNTIME.statPublished }}</p>
        <p
          class="mt-1 text-2xl font-semibold tabular-nums"
          :class="
            runtimeStats.published === runtimeStats.total ? 'text-emerald-300' : 'text-white'
          "
        >
          {{ runtimeStats.published }}
          <span class="text-base font-normal text-slate-500">/ {{ runtimeStats.total }}</span>
        </p>
      </div>
      <div class="admin-panel admin-tool-registry-stat-card rounded-lg px-4 py-3">
        <p class="text-xs text-slate-500">{{ SKILL_REGISTRY_PAGE.statToolsEnabled }}</p>
        <p class="mt-1 text-2xl font-semibold tabular-nums text-white">
          {{ stats.bOn + stats.cOn }}
          <span class="text-base font-normal text-slate-500">
            / {{ stats.bTotal + stats.cTotal }}
          </span>
        </p>
      </div>
      <div class="admin-panel admin-tool-registry-stat-card rounded-lg px-4 py-3">
        <p class="text-xs text-slate-500">{{ SKILL_REGISTRY_PAGE.statAudit }}</p>
        <p class="mt-1 text-2xl font-semibold tabular-nums text-white">{{ stats.audit }}</p>
      </div>
    </div>

    <div
      class="mb-4 rounded-lg border border-sky-500/25 bg-sky-500/10 px-4 py-3 text-sm leading-relaxed text-sky-100/95"
      role="note"
    >
      <p class="font-medium text-sky-100">{{ SKILL_REGISTRY_PAGE.alertTitle }}</p>
      <p class="mt-1 text-sky-100/90">{{ SKILL_REGISTRY_PAGE.alertDescription }}</p>
    </div>

    <section class="admin-panel overflow-hidden">
      <div class="border-b border-slate-800/90 px-4 py-3 sm:px-5">
        <h2 class="text-[15px] font-semibold text-white">{{ SKILL_REGISTRY_PAGE.cardTitle }}</h2>
      </div>
      <div class="space-y-4 p-4 sm:p-5">
        <div class="flex flex-wrap gap-2 border-b border-slate-800 pb-2">
          <button
            v-for="tab in [
              {
                key: 'skills' as const,
                label: SKILL_REGISTRY_PAGE.tabTrading,
                count: filteredSkillRows.length,
                total: skillListFiltered.length,
              },
              { key: 'tools-b' as const, label: SKILL_REGISTRY_PAGE.tabReadonly, count: MOCK_TOOL_B_ROWS.length },
              { key: 'tools-c' as const, label: SKILL_REGISTRY_PAGE.tabExternal, count: MOCK_TOOL_C_ROWS.length },
              { key: 'audit' as const, label: SKILL_REGISTRY_PAGE.tabAudit, count: store.audit.length },
            ]"
            :key="tab.key"
            type="button"
            class="admin-seg inline-flex items-center gap-2 text-xs sm:text-sm"
            :class="
              activeTab === tab.key
                ? 'admin-seg-active'
                : 'admin-seg-idle hover:bg-slate-800/65 hover:text-slate-200'
            "
            @click="activeTab = tab.key"
          >
            <span>{{ tab.label }}</span>
            <UiStatChip v-if="tab.key !== 'audit' || tab.count > 0" tone="neutral">
              <template v-if="tab.key === 'skills' && skillTableFiltered">
                {{ tab.count }} / {{ tab.total }}
              </template>
              <template v-else>{{ tab.count }}</template>
            </UiStatChip>
          </button>
        </div>

        <div v-if="activeTab === 'skills'" class="space-y-3">
          <div class="flex flex-wrap items-center gap-2">
            <UiInput
              v-model="skillFilter"
              size="sm"
              class="max-w-md flex-1"
              :placeholder="SKILL_REGISTRY_PAGE.searchPlaceholder"
              aria-label="搜索技能"
            />
            <button
              type="button"
              class="admin-seg inline-flex items-center text-xs sm:text-sm"
              :class="
                showPublishedOnly
                  ? 'admin-seg-active'
                  : 'admin-seg-idle hover:bg-slate-800/65 hover:text-slate-200'
              "
              :aria-pressed="showPublishedOnly"
              @click="showPublishedOnly = !showPublishedOnly"
            >
              {{ SKILL_REGISTRY_PAGE.filterPublishedOnly }}
            </button>
          </div>
          <SkillRegistryTable
            :rows="filteredSkillRows"
            :store="store"
            :active-skill-id="detailSkillId"
            :loading="loading"
            :filtered="skillTableFiltered && mergedRows.length > 0"
            @toggle="onSkillToggle"
            @open-drawer="openSkillDetail"
          />
        </div>

        <div
          v-else-if="activeTab === 'tools-b' || activeTab === 'tools-c'"
          class="overflow-hidden rounded-lg border-0"
          :class="adminTableHostOverflowClass(true)"
        >
          <table class="w-full min-w-[40rem] table-fixed text-left text-sm">
            <thead class="border-b border-slate-800 bg-slate-900/85 text-xs uppercase tracking-wide text-slate-500">
              <tr>
                <th class="w-[240px] px-4 py-3 align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.colTool }}</th>
                <th class="min-w-0 px-4 py-3 align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.colDesc }}</th>
                <th class="w-24 px-4 py-3 text-center align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.colStatus }}</th>
                <th class="w-20 px-4 py-3 text-center align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.colEnabled }}</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-800/90">
              <tr
                v-for="row in activeTab === 'tools-b' ? MOCK_TOOL_B_ROWS : MOCK_TOOL_C_ROWS"
                :key="row.stableId"
                class="align-middle"
                :class="toolRowClass(row)"
              >
                <td class="px-4 py-3 align-top">
                  <p class="text-sm font-medium text-slate-100">{{ row.summary }}</p>
                  <p class="mt-0.5 font-mono text-[11px] text-slate-500">{{ row.stableId }}</p>
                </td>
                <td class="min-w-0 px-4 py-3 align-top text-xs leading-relaxed text-slate-400">
                  {{ row.anchor }}
                </td>
                <td class="px-4 py-3 text-center align-middle">
                  <span
                    class="inline-flex rounded border px-2 py-0.5 text-[11px] font-medium"
                    :class="matrixStatusClass(row.matrixStatus)"
                  >
                    {{ matrixStatusLabel(row.matrixStatus) }}
                  </span>
                </td>
                <td class="px-4 py-3 text-center align-middle">
                  <UiEnableCheckbox
                    :model-value="toolRowEnabled(row)"
                    :aria-label="`${row.summary} 启用`"
                    @update:model-value="onToolToggle(row, $event)"
                  />
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div
          v-else
          class="overflow-hidden rounded-lg border-0"
          :class="adminTableHostOverflowClass(auditRows.length > 0)"
        >
          <table class="w-full min-w-[40rem] table-fixed text-left text-sm">
            <thead class="border-b border-slate-800 bg-slate-900/85 text-xs uppercase tracking-wide text-slate-500">
              <tr>
                <th class="w-[200px] px-4 py-3 align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.auditTime }}</th>
                <th class="w-16 px-4 py-3 text-center align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.auditType }}</th>
                <th class="min-w-0 px-4 py-3 align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.auditId }}</th>
                <th class="w-20 px-4 py-3 text-center align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.auditAction }}</th>
                <th class="w-24 px-4 py-3 align-bottom font-medium" scope="col">{{ TOOL_REGISTRY_TABLE.auditActor }}</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-800/90">
              <UiTableEmptyRow
                v-if="auditRows.length === 0"
                :colspan="5"
                :empty-text="TOOL_REGISTRY_TABLE.auditEmpty"
              />
              <tr v-for="(entry, idx) in auditRows" :key="`${entry.at}-${entry.stableId}-${idx}`" class="align-middle">
                <td class="px-4 py-3">
                  <code class="font-mono text-[11px] text-slate-400">{{ entry.at }}</code>
                </td>
                <td class="px-4 py-3 text-center">
                  <UiStatChip
                    :tone="entry.entryClass === 'A' ? 'violet' : entry.entryClass === 'B' ? 'info' : 'neutral'"
                  >
                    {{ entry.entryClass }}
                  </UiStatChip>
                </td>
                <td class="min-w-0 px-4 py-3">
                  <code class="block truncate font-mono text-[11px] text-slate-400">{{ entry.stableId }}</code>
                </td>
                <td class="px-4 py-3 text-center">
                  <UiStatChip :tone="entry.enabled ? 'success' : 'neutral'">
                    {{ entry.enabled ? '启用' : '停用' }}
                  </UiStatChip>
                </td>
                <td class="px-4 py-3 text-xs text-slate-400">{{ entry.actor }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </section>

    <SkillOperationDrawer
      :skill-id="detailSkillId"
      :row="detailRow"
      @close="closeDrawer"
      @published="onPublished"
    />
  </AdminPage>
</template>

// product-doc/src/admin/src/pages/tools/ToolRegistryPage.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { ReloadOutlined, SearchOutlined } from "@ant-design/icons";
import {
  App,
  Button,
  Card,
  Col,
  Input,
  Row,
  Space,
  Statistic,
  Switch,
  Table,
  Tabs,
  Tag,
  Typography,
} from "antd";
import type { ColumnsType } from "antd/es/table";
import { ProductPageShell, useAdminTablePagination } from "../../components/product";
import {
  MOCK_SKILL_REGISTRY_ROWS,
  MOCK_TOOL_B_ROWS,
  MOCK_TOOL_C_ROWS,
  type ToolRegistryRow,
} from "../../data/toolRegistryMock";
import {
  loadToolRegistryState,
  persistToggle,
  resetToolRegistryDemo,
  type ToolRegistryStored,
} from "./toolRegistryStorage";
import { SkillOperationDrawer } from "./SkillOperationDrawer";
import { SkillRegistryTable } from "./SkillRegistryTable";
import { matrixStatusTag } from "./skillRegistryDisplay";
import {
  SKILL_REGISTRY_PAGE,
  SKILL_TABLE,
  TOOL_REGISTRY_TABLE,
} from "./skillRegistryUiCopy";

const { Paragraph, Text, Title } = Typography;

function isRowEnabled(row: ToolRegistryRow, store: ToolRegistryStored): boolean {
  return store.enabled[row.stableId] ?? row.defaultEnabled;
}

function RegistryTable({
  columns,
  data,
  store,
  paginationResetKey,
  rowClassName,
}: {
  columns: ColumnsType<ToolRegistryRow>;
  data: ToolRegistryRow[];
  store: ToolRegistryStored;
  paginationResetKey?: string;
  rowClassName?: (row: ToolRegistryRow) => string;
}) {
  const { pagination, slice } = useAdminTablePagination(data.length, { resetKey: paginationResetKey });
  const pageRows = slice(data);

  return (
    <Table<ToolRegistryRow>
      className="admin-tool-registry-table"
      size="middle"
      rowKey="stableId"
      pagination={pagination}
      bordered
      scroll={{ x: "max-content" }}
      columns={columns}
      dataSource={pageRows}
      locale={{ emptyText: SKILL_TABLE.empty }}
      rowClassName={(record) => rowClassName?.(record) ?? ""}
    />
  );
}

function renderRegistryTable(
  columns: ColumnsType<ToolRegistryRow>,
  data: ToolRegistryRow[],
  store: ToolRegistryStored,
  paginationResetKey?: string,
  rowClassName?: (row: ToolRegistryRow) => string,
) {
  return (
    <RegistryTable
      columns={columns}
      data={data}
      store={store}
      paginationResetKey={paginationResetKey}
      rowClassName={rowClassName}
    />
  );
}

export function ToolRegistryPage() {
  const { message } = App.useApp();
  const allRows = useMemo(
    () => [...MOCK_SKILL_REGISTRY_ROWS, ...MOCK_TOOL_B_ROWS, ...MOCK_TOOL_C_ROWS],
    [],
  );
  const defaultEnabledMap = useMemo(() => {
    const m: Record<string, boolean> = {};
    for (const r of allRows) m[r.stableId] = r.defaultEnabled;
    return m;
  }, [allRows]);
  const allIds = useMemo(() => allRows.map((r) => r.stableId), [allRows]);

  const [store, setStore] = useState<ToolRegistryStored>(() =>
    loadToolRegistryState(allIds, defaultEnabledMap),
  );
  const [detailSkillId, setDetailSkillId] = useState<string | null>(null);
  const [skillFilter, setSkillFilter] = useState("");

  const filteredSkillRows = useMemo(() => {
    const kw = skillFilter.trim().toLowerCase();
    if (!kw) return MOCK_SKILL_REGISTRY_ROWS;
    return MOCK_SKILL_REGISTRY_ROWS.filter(
      (r) =>
        r.stableId.toLowerCase().includes(kw) ||
        r.summary.toLowerCase().includes(kw) ||
        (r.userFlow ?? "").toLowerCase().includes(kw) ||
        (r.exchangeAction ?? "").toLowerCase().includes(kw),
    );
  }, [skillFilter]);

  const stats = useMemo(() => {
    const countOn = (rows: ToolRegistryRow[]) =>
      rows.filter((r) => isRowEnabled(r, store)).length;
    return {
      aOn: countOn(MOCK_SKILL_REGISTRY_ROWS),
      aTotal: MOCK_SKILL_REGISTRY_ROWS.length,
      bOn: countOn(MOCK_TOOL_B_ROWS),
      bTotal: MOCK_TOOL_B_ROWS.length,
      cOn: countOn(MOCK_TOOL_C_ROWS),
      cTotal: MOCK_TOOL_C_ROWS.length,
      audit: store.audit.length,
    };
  }, [store]);

  const onToggle = useCallback(
    (row: ToolRegistryRow, checked: boolean) => {
      if (row.matrixStatus === "tbd" && checked) {
        message.warning(SKILL_REGISTRY_PAGE.enableWarning);
      }
      setStore((prev) =>
        persistToggle({
          allIds,
          rowDefaults: defaultEnabledMap,
          stableId: row.stableId,
          entryClass: row.entryClass,
          enabled: checked,
          prev,
        }),
      );
    },
    [allIds, defaultEnabledMap, message],
  );

  const resetDemo = useCallback(() => {
    setStore(resetToolRegistryDemo(allIds, defaultEnabledMap));
    message.success(SKILL_REGISTRY_PAGE.resetSuccess);
  }, [allIds, defaultEnabledMap, message]);

  const openSkillDetail = useCallback((skillId: string) => {
    setDetailSkillId(skillId);
  }, []);

  const toolColumns: ColumnsType<ToolRegistryRow> = useMemo(
    () => [
      {
        title: TOOL_REGISTRY_TABLE.colTool,
        dataIndex: "stableId",
        key: "stableId",
        width: 260,
        render: (id: string, record) => (
          <>
            <Text strong>{record.summary}</Text>
            <br />
            <Text code copyable={{ text: id }} style={{ fontSize: 12 }}>
              {id}
            </Text>
          </>
        ),
      },
      {
        title: TOOL_REGISTRY_TABLE.colDesc,
        dataIndex: "anchor",
        key: "anchor",
        ellipsis: { showTitle: true },
        render: (t: string) => (
          <Text type="secondary" style={{ fontSize: 13 }}>
            {t}
          </Text>
        ),
      },
      {
        title: TOOL_REGISTRY_TABLE.colStatus,
        dataIndex: "matrixStatus",
        key: "matrixStatus",
        width: 96,
        align: "center",
        render: (s: ToolRegistryRow["matrixStatus"]) => matrixStatusTag(s),
      },
      {
        title: TOOL_REGISTRY_TABLE.colEnabled,
        key: "enabled",
        width: 88,
        align: "center",
        fixed: "right",
        render: (_: unknown, record) => (
          <Switch
            checked={isRowEnabled(record, store)}
            onChange={(c) => onToggle(record, c)}
            size="small"
          />
        ),
      },
    ],
    [onToggle, store],
  );

  const auditColumns: ColumnsType<ToolRegistryStored["audit"][0]> = [
    {
      title: TOOL_REGISTRY_TABLE.auditTime,
      dataIndex: "at",
      key: "at",
      width: 200,
      render: (t) => <Text code>{t}</Text>,
    },
    {
      title: TOOL_REGISTRY_TABLE.auditType,
      dataIndex: "entryClass",
      key: "c",
      width: 48,
      align: "center",
      render: (c: string) => (
        <Tag bordered={false} color={c === "A" ? "magenta" : c === "B" ? "blue" : "geekblue"}>
          {c}
        </Tag>
      ),
    },
    {
      title: TOOL_REGISTRY_TABLE.auditId,
      dataIndex: "stableId",
      key: "id",
      ellipsis: true,
      render: (id) => (
        <Text code copyable={{ text: id }}>
          {id}
        </Text>
      ),
    },
    {
      title: TOOL_REGISTRY_TABLE.auditAction,
      dataIndex: "enabled",
      key: "en",
      width: 72,
      align: "center",
      render: (e: boolean) =>
        e ? (
          <Tag bordered={false} color="processing">
            启用
          </Tag>
        ) : (
          <Tag bordered={false}>停用</Tag>
        ),
    },
    { title: TOOL_REGISTRY_TABLE.auditActor, dataIndex: "actor", key: "actor", width: 100 },
  ];

  return (
    <div className="admin-tool-registry-page">
      <ProductPageShell
        title={SKILL_REGISTRY_PAGE.title}
        pageId="ai.tool-registry"
        tags={
          <>
            <Tag color="processing">{SKILL_REGISTRY_PAGE.tagTrading}</Tag>
            <Tag>{SKILL_REGISTRY_PAGE.tagPreview}</Tag>
          </>
        }
        description={
          <Paragraph type="secondary" style={{ marginBottom: 0, maxWidth: 880 }}>
            {SKILL_REGISTRY_PAGE.description}
          </Paragraph>
        }
        extra={
          <Button icon={<ReloadOutlined />} onClick={resetDemo}>
            {SKILL_REGISTRY_PAGE.resetButton}
          </Button>
        }
      >
        <Row gutter={[12, 12]} className="admin-tool-registry-stats" style={{ marginBottom: 16 }}>
          <Col xs={12} sm={12} lg={6}>
            <Card size="small" className="admin-panel-card admin-tool-registry-stat-card">
              <Statistic
                title={SKILL_REGISTRY_PAGE.statTradingEnabled}
                value={stats.aOn}
                suffix={`/ ${stats.aTotal}`}
              />
            </Card>
          </Col>
          <Col xs={12} sm={12} lg={6}>
            <Card size="small" className="admin-panel-card admin-tool-registry-stat-card">
              <Statistic
                title={SKILL_REGISTRY_PAGE.statToolsEnabled}
                value={stats.bOn + stats.cOn}
                suffix={`/ ${stats.bTotal + stats.cTotal}`}
              />
            </Card>
          </Col>
          <Col xs={12} sm={12} lg={6}>
            <Card size="small" className="admin-panel-card admin-tool-registry-stat-card">
              <Statistic title={SKILL_REGISTRY_PAGE.statAudit} value={stats.audit} />
            </Card>
          </Col>
        </Row>

        <Card
          size="small"
          className="admin-panel-card"
          title={
            <Title level={5} style={{ margin: 0 }}>
              {SKILL_REGISTRY_PAGE.cardTitle}
            </Title>
          }
          styles={{ body: { paddingTop: 12 } }}
        >
          <Tabs
            className="admin-tool-registry-tabs"
            defaultActiveKey="skills"
            destroyInactiveTabPane
            items={[
              {
                key: "skills",
                label: (
                  <Space size={6}>
                    <span>{SKILL_REGISTRY_PAGE.tabTrading}</span>
                    <Tag bordered={false} color="magenta" style={{ marginInlineEnd: 0 }}>
                      {filteredSkillRows.length}
                      {skillFilter.trim() ? ` / ${MOCK_SKILL_REGISTRY_ROWS.length}` : ""}
                    </Tag>
                  </Space>
                ),
                children: (
                  <>
                    <Input
                      allowClear
                      prefix={<SearchOutlined style={{ color: "rgba(0,0,0,0.25)" }} />}
                      placeholder={SKILL_REGISTRY_PAGE.searchPlaceholder}
                      value={skillFilter}
                      onChange={(e) => setSkillFilter(e.target.value)}
                      style={{ maxWidth: 360, marginBottom: 12 }}
                    />
                    <SkillRegistryTable
                      rows={filteredSkillRows}
                      store={store}
                      activeSkillId={detailSkillId}
                      paginationResetKey={skillFilter}
                      onToggle={onToggle}
                      onOpenDrawer={openSkillDetail}
                    />
                  </>
                ),
              },
              {
                key: "tools-b",
                label: (
                  <Space size={6}>
                    <span>{SKILL_REGISTRY_PAGE.tabReadonly}</span>
                    <Tag bordered={false} color="blue" style={{ marginInlineEnd: 0 }}>
                      {MOCK_TOOL_B_ROWS.length}
                    </Tag>
                  </Space>
                ),
                children: renderRegistryTable(toolColumns, MOCK_TOOL_B_ROWS, store),
              },
              {
                key: "tools-c",
                label: (
                  <Space size={6}>
                    <span>{SKILL_REGISTRY_PAGE.tabExternal}</span>
                    <Tag bordered={false} color="geekblue" style={{ marginInlineEnd: 0 }}>
                      {MOCK_TOOL_C_ROWS.length}
                    </Tag>
                  </Space>
                ),
                children: renderRegistryTable(toolColumns, MOCK_TOOL_C_ROWS, store),
              },
              {
                key: "audit",
                label: (
                  <Space size={6}>
                    <span>{SKILL_REGISTRY_PAGE.tabAudit}</span>
                    {store.audit.length > 0 ? (
                      <Tag bordered={false} style={{ marginInlineEnd: 0 }}>
                        {store.audit.length}
                      </Tag>
                    ) : null}
                  </Space>
                ),
                children: (
                  <Table
                    className="admin-tool-registry-table"
                    size="middle"
                    bordered
                    rowKey={(r) => `${r.at}-${r.stableId}`}
                    pagination={{ pageSize: 10, showSizeChanger: false }}
                    columns={auditColumns}
                    dataSource={[...store.audit].reverse()}
                    locale={{ emptyText: TOOL_REGISTRY_TABLE.auditEmpty }}
                  />
                ),
              },
            ]}
          />
        </Card>

        <SkillOperationDrawer skillId={detailSkillId} onClose={() => setDetailSkillId(null)} />
      </ProductPageShell>
    </div>
  );
}
